# Generated by Django 5.2.13 on 2026-04-27 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'escola',
                'verbose_name_plural': 'escolas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.escola')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfis de usuario',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Nao Especificado', 'Nao Especificado')], max_length=50)),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Numero')),
                ('zona', models.CharField(blank=True, choices=[('Urbana', 'Zona Urbana'), ('Rural', 'Zona Rural')], max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=255, verbose_name='Bairro / Vila')),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('escolaridade', models.CharField(blank=True, choices=[('Ensino Fundamental', 'Ensino Fundamental'), ('Ensino Medio', 'Ensino Medio'), ('Ensino Superior', 'Ensino Superior')], max_length=50)),
                ('formacao', models.CharField(blank=True, max_length=255, verbose_name='Formacao')),
                ('instituicao', models.CharField(blank=True, max_length=255, verbose_name='Instituicao')),
                ('funcao', models.CharField(blank=True, max_length=100, verbose_name='Funcao')),
                ('cargo', models.CharField(blank=True, choices=[('Secretario(a)', 'Secretario(a)'), ('Assistente Administrativo', 'Assistente Administrativo'), ('Auxiliar Administrativo', 'Auxiliar Administrativo'), ('ASG', 'ASG'), ('Coordenador(a)', 'Coordenador(a)'), ('Professor(a)', 'Professor(a)'), ('Vigia', 'Vigia'), ('Merendeira', 'Merendeira'), ('Monitor(a)', 'Monitor(a)'), ('Motorista', 'Motorista'), ('Diretor(a)', 'Diretor(a)'), ('Mediadora Social', 'Mediadora Social')], max_length=100)),
                ('vinculo', models.CharField(blank=True, choices=[('Efetivo', 'Efetivo'), ('Temporario', 'Temporario')], max_length=100, verbose_name='Vinculo')),
                ('carga_horaria', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga horaria')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de admissao')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de inicio')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saida')),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=20, verbose_name='Agencia')),
                ('conta', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='core.escola')),
            ],
            options={
                'verbose_name': 'servidor',
                'verbose_name_plural': 'servidores',
                'ordering': ['nome'],
            },
        ),
    ]
