# Generated by Django 5.2.13 on 2026-04-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Marco'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro'), ('13', 'Decimo Terceiro'), ('14', 'Ferias')], max_length=2)),
                ('ano', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4)),
                ('faltas', models.PositiveSmallIntegerField(default=0)),
                ('observacoes', models.CharField(blank=True, choices=[('', ''), ('LICENCA SEM VENCIMENTO', 'Licenca sem vencimento'), ('LICENCA MATERNIDADE', 'Licenca maternidade'), ('LICENCA PREMIO', 'Licenca premio'), ('LICENCA PARA ESTUDO', 'Licenca para estudo'), ('FERIAS', 'Ferias'), ('FALTA', 'Falta'), ('PRO-LABORE', 'Pro-labore'), ('DIARIA', 'Diaria'), ('DOBRA DE TURNO', 'Dobra de turno'), ('ATESTADO MEDICO', 'Atestado medico'), ('DECIMO TERCEIRO', 'Decimo terceiro'), ('DESLIGAMENTO', 'Desligamento'), ('INSS', 'INSS'), ('OUTROS', 'Outros')], max_length=80)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='core.servidor')),
            ],
            options={
                'verbose_name': 'frequencia',
                'verbose_name_plural': 'frequencias',
                'ordering': ['servidor__nome'],
                'unique_together': {('servidor', 'mes', 'ano')},
            },
        ),
    ]
