# Generated by Django 5.2.13 on 2026-04-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_frequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='ano',
            field=models.CharField(choices=[('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4),
        ),
    ]
