# Generated by Django 5.2.13 on 2026-05-09 17:02

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def criar_acesso_semed(apps, schema_editor):
    Escola = apps.get_model('core', 'Escola')
    PerfilUsuario = apps.get_model('core', 'PerfilUsuario')
    User = apps.get_model('auth', 'User')

    escola, _ = Escola.objects.get_or_create(nome='SEMED', defaults={'ativa': True})
    user, created = User.objects.get_or_create(
        username='semed',
        defaults={'is_active': True, 'first_name': 'SEMED'},
    )
    user.first_name = user.first_name or 'SEMED'
    user.is_active = True
    user.password = make_password('Escola@2026')
    user.save()
    PerfilUsuario.objects.update_or_create(usuario=user, defaults={'escola': escola})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_folhapdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='motivo_inativo',
            field=models.CharField(blank=True, choices=[('', ''), ('Licenca', 'Licença'), ('Aposentado', 'Aposentado'), ('Obito', 'Óbito'), ('Outros', 'Outros')], max_length=30),
        ),
        migrations.CreateModel(
            name='TransferenciaServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('escola_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='core.escola')),
                ('escola_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='core.escola')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_respondidas', to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='core.servidor')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transferência de servidor',
                'verbose_name_plural': 'transferências de servidores',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RunPython(criar_acesso_semed, migrations.RunPython.noop),
    ]
