# Generated by Django 5.2.13 on 2026-05-09 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servidor_motivo_inativo_transferenciaservidor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Marco'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro'), ('13', 'Decimo Terceiro'), ('14', 'Ferias')], max_length=2)),
                ('ano', models.CharField(choices=[('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4)),
                ('campo', models.CharField(max_length=40)),
                ('valor_anterior', models.CharField(blank=True, max_length=120)),
                ('valor_novo', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes_folha', to='core.escola')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes_folha', to='core.servidor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alteração da folha',
                'verbose_name_plural': 'alterações das folhas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
