# Generated by Django 5.2.13 on 2026-05-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_folhaalteracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='licenca_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='licenca_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='licenca_tipo',
            field=models.CharField(blank=True, choices=[('', ''), ('LICENCA PREMIO', 'Licença prêmio'), ('LICENCA MATERNIDADE', 'Licença maternidade'), ('LICENCA PARA ESTUDO', 'Licença para estudo')], max_length=40),
        ),
    ]
