# Generated by Django 5.2.13 on 2026-05-10 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servidor_licenca_fim_servidor_licenca_inicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Marco'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro'), ('13', 'Decimo Terceiro'), ('14', 'Ferias')], max_length=2)),
                ('ano', models.CharField(choices=[('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4)),
                ('motivo', models.CharField(blank=True, max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusoes_folha', to='core.servidor')),
            ],
            options={
                'verbose_name': 'exclusão da folha',
                'verbose_name_plural': 'exclusões das folhas',
                'ordering': ['servidor__nome'],
                'unique_together': {('servidor', 'mes', 'ano')},
            },
        ),
    ]
