# Generated by Django 5.2.13 on 2026-05-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_folhaexclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='cargo',
            field=models.CharField(blank=True, choices=[('Secretario(a)', 'Secretario(a)'), ('Secretaria de Educacao', 'Secretária de Educação'), ('Assistente Administrativo', 'Assistente Administrativo'), ('Auxiliar Administrativo', 'Auxiliar Administrativo'), ('ASG', 'ASG'), ('Coordenador(a)', 'Coordenador(a)'), ('Coordenador(a) Pedagogico', 'Coordenador(a) Pedagógico'), ('Coordenador(a) de Sistemas', 'Coordenador(a) de Sistemas'), ('Professor(a)', 'Professor(a)'), ('Vigia', 'Vigia'), ('Merendeira', 'Merendeira'), ('Monitor(a)', 'Monitor(a)'), ('Motorista', 'Motorista'), ('Diretor(a)', 'Diretor(a)'), ('Mediadora Social', 'Mediadora Social')], max_length=100),
        ),
    ]
