# Generated by Django 5.2.13 on 2026-05-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_servidorobservacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='pro_labore_horas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Horas de pró-labore'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='observacoes',
            field=models.CharField(blank=True, choices=[('', ''), ('LICENCA SEM VENCIMENTO', 'Licenca sem vencimento'), ('LICENCA MATERNIDADE', 'Licenca maternidade'), ('LICENCA PREMIO', 'Licenca premio'), ('LICENCA PARA ESTUDO', 'Licenca para estudo'), ('FERIAS', 'Ferias'), ('FALTA', 'Falta'), ('PRO-LABORE', 'Pró-Labore'), ('DIARIA', 'Diaria'), ('DOBRA DE TURNO', 'Dobra de turno'), ('ATESTADO MEDICO', 'Atestado medico'), ('DECIMO TERCEIRO', 'Decimo terceiro'), ('DESLIGAMENTO', 'Desligamento'), ('INSS', 'INSS'), ('OUTROS', 'Outros')], max_length=80),
        ),
    ]
